name: Hello world

on: 
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
    - run: echo "hello world"
  
  say-hello-inline-python:
    runs-on: ubuntu-24.04
    steps:
      - run: print("Hello World from python)
        shell: python
